<div class="template">
    <button class="btn1">
        <span><?= $block->escapeHtml(__('Open Modal')) ?></span>
    </button>

    <button class="btn2">
        <span><?= $block->escapeHtml(__('Open Custom Login Modal')) ?></span>
    </button>

    <button class="btn3">
        <span><?= $block->escapeHtml(__('Open Magento Login Modal')) ?></span>
    </button>

    <div class="btn2_promt">
        <div class="modal-body-content">
            <h2><?= $block->escapeHtml(__('Title')) ?></h2>
            <p><?= $block->escapeHtml(__('Content')) ?></p>
        </div>
    </div>

    <div class="login_promt">
        <div class="modal-body-content">
            <div class="login-modal" class='authentication-popup-template' data-bind="scope: 'authentication-popup'">
                <!-- ko template: getTemplate() -->
                <!-- /ko  -->
                <script type="text/x-magento-init">
                    {
                        "#authentication-popup-template": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "authentication-popup": {
                                        "component": "AHT_FrontendTest/js/authentication-popup",
                                        "template" : "AHT_FrontendTest/modal",
                                        "children": {
                                            "messages":{
                                                "component":"Magento_Ui/js/view/messages",
                                                "displayArea":"messages"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                </script>
            </div>
        </div>
    </div>

</div>
<script type="text/javascript">
    require([
        'jquery',
        "Magento_Ui/js/modal/modal",
        'Magento_Customer/js/model/authentication-popup'
    ], function($, modal, auth) {
        var popup1 = modal({
            type: 'popup',
            responsive: true,
            title: 'Main title',
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function() {
                    this.closeModal();
                }
            }]
        }, $('.btn2_promt'));

        var popup2 = modal({
            type: 'popup',
            responsive: true,
            title: 'Login Modal',
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function() {
                    this.closeModal();
                }
            }]
        }, $('.login_promt'));

        $(".btn1").click(function() {
            $('.btn2_promt').modal('openModal');
        });

        $(".btn2").click(function() {
            $('.login_promt').modal('openModal');
        });

        $(".btn3").click(function() {
            auth.showModal();
        });
    })
</script>
